### ISSUE TITLE
Is there an offical build anywhere?

### ISSUE THREAD

**Issue by nevster** [openemulator/openemulator#23]
I'd like to get a new build with the .woz format support.
I can build it myself but I was just wondering if there was an official build somewhere?

**Comment by zellyn** [comment]
https://archive.org/details/OpenEmulatorSnapshots

**Comment by nevster** [comment]
Awesome - thank you!

**Comment by nevster** [comment]
Can I suggest you add that to the top of the Readme?

**Comment by tobier** [comment]
I'm working on better dependency management and continuous integration, which should make it easier to make functioning builds. Not sure if Travis can produce application packages but I will look into it.
